#!/bin/sh

cd `dirname $0`

if [ "$1" = "" ]; then
	echo "Usage: ${0} <version>"
	exit;
fi

echo "Downloading PolarSSL version ${1}."
wget -qO polarssl.tgz https://polarssl.org/download/polarssl-${1}-gpl.tgz?do=yes

if [ ! -s polarssl.tgz ]; then 
	rm -f polarssl.tgz
	echo "Download error."
	exit
fi

echo "Removing current PolarSSL library."
rm -rf include
rm -rf library

echo "Installing new PolarSSL library."
tar -xzf polarssl.tgz
dir=`tar -tzf polarssl.tgz | head -n1`
mv ${dir}ChangeLog .
mv ${dir}include .
mv ${dir}library .

echo "Cleaning up."
rm -f include/.gitignore
rm -f library/.gitignore
rm -rf ${dir}
rm polarssl.tgz

echo "PolarSSL upgraded to version ${1}."
